### PR TITLE
WIP: Tekton Pipeline Objects

### PR DESCRIPTION
**Pull request by NautiluX**

### CODE REVIEW

**Comment by georgettica** [comment]
does this work better than `test-integration`?

**Review by NautiluX — COMMENTED** [review]
Thanks for this PR, can you add a short readme describing how to use it?

**Comment by NautiluX** [comment]
> does this work better than `test-integration`?

this will run on a cluster that has RMO deployed already, it's a different usecase than the test-integration script. You still have issues with the GCP deployed CRC?

**Comment by georgettica** [comment]
The only issue is that passing the image up to gxp takes forever so I use https://www.cis.upenn.edu/~bcpierce/unison/ to copy to gxp and run `test-integration` there

**Pull request merged**
