### PR TITLE
feat(project): make repo v3 complient

### PR DESCRIPTION
**Pull request by georgettica**
it seems the error https://github.com/operator-framework/operator-sdk/blob/74f5a36af68489d8e3d857f2fedbffacf207474e/internal/cmd/operator-sdk/generate/internal/genutil.go#L163 requires adding this

maybe more operations are required, but I didn't look deeper

### CODE REVIEW

**Comment by georgettica** [comment]
/hold
there may be stuff that needs to happen aswell to make the migration successfull, that is all I needed for it to work

**Comment by RiRa12621** [comment]
We don't care about v3 anymkfe

**Pull request merged**
