### PR TITLE
hack: adjust file location after build

### PR DESCRIPTION
**Pull request by RiRa12621**
We need our files to be in /registry/manifests and not /registry/manifests/route-monitor-operator

### CODE REVIEW

**Comment by RiRa12621** [comment]
/hold
wait for monday
/assign @NautiluX 
/cc @jharrington22 
Makes sense james?

**Review by georgettica — COMMENTED** [review]
How can we test it's ok?

**Comment by RiRa12621** [comment]
I'll explain a bit on Monday and afterward add it to the readme

**Comment by georgettica** [comment]
@RiRa12621 this can be dropped as we solved this in a different manner

**Comment by RiRa12621** [comment]
Can you reference the other PR so it's easier to follow up please @georgettica

**Comment by georgettica** [comment]
For sure #47

**Pull request closed without merging**
