### PR TITLE
Cleanup after integration test

### PR DESCRIPTION
**Pull request by NautiluX**
* Removing project after integration test is finished
* Switch to `oc adm new-project` to create namespace

### CODE REVIEW

**Comment by RiRa12621** [comment]
/lgtm
HELL YEAH!
awesome job right there @NautiluX

**Review by RiRa12621 — APPROVED** [review]

**Comment by Tessg22** [comment]
@NautiluX Why [in this line](https://github.com/openshift/route-monitor-operator/blob/9e5b66a305c4eeffd66bb7bd85f56914284146c4/hack/test-integration.sh#L5) is exported KUBECONFIG when it is not used in the script?

**Comment by Tessg22** [comment]
Second point, I searched through all rmo code and test-integration script is the only place where chosen namespace gets created. This seems odd to me.
`oc adm new-project "$NAMESPACE" || true`

Otherwise I get this errors from make deploy.
`clusterrolebinding.rbac.authorization.k8s.io/route-monitor-operator-manager-rolebinding created
Error from server (NotFound): error when creating "STDIN": namespaces "openshift-route-monitor-operator" not found
Error from server (NotFound): error when creating "STDIN": namespaces "openshift-route-monitor-operator" not found
Error from server (NotFound): error when creating "STDIN": namespaces "openshift-route-monitor-operator" not found
Error from server (NotFound): error when creating "STDIN": namespaces "openshift-route-monitor-operator" not found`

Running $ oc adm new-project "$NAMESPACE" manually solves the issue.

**Comment by RiRa12621** [comment]
> @NautiluX Why [in this line](https://github.com/openshift/route-monitor-operator/blob/9e5b66a305c4eeffd66bb7bd85f56914284146c4/hack/test-integration.sh#L5) is exported KUBECONFIG when it is not used in the script?

This is so we have a way to run the OC commands without explicitly declaring where the config is on each line

**Comment by Tessg22** [comment]
Thank you Rick :)

**Pull request merged**
