### PR TITLE
Boilerplate update 1 180f2994b9c9068136c0ca131cb3bf8bb1a23e96

### PR DESCRIPTION
**Pull request by NautiluX**

### CODE REVIEW

**Comment by georgettica** [comment]
should the diff not be visible in github aswell after adding https://github.com/openshift/route-monitor-operator/pull/114/files#diff-618cd5b83d62060ba3d027e314a21ceaf75d36067ff820db126642944145393eR1

@NautiluX ?

**Comment by 2uasimojo** [comment]
> should the diff not be visible in github aswell after adding https://github.com/openshift/route-monitor-operator/pull/114/files#diff-618cd5b83d62060ba3d027e314a21ceaf75d36067ff820db126642944145393eR1
> 
> @NautiluX ?

Most of the boilerplate files are hidden, as you can see. But for security, we deliberately show the files that a malicious user would have to hack to subvert the “boilerplate files are unchanged from their original form” thing.

**Comment by RiRa12621** [comment]
/hold
What's the benefit/risk of this?

**Comment by 2uasimojo** [comment]
> What's the benefit/risk of this?

See the [auto bp update commit](https://github.com/openshift/route-monitor-operator/pull/114/commits/64a7b36a41d5a4511fb5b4b5217e309e0907fbe5) for the bp changes that this brings in. For the most part, they'll be transparent to RMO. But you may notice improvements to tooling such as `container-make` being more podman-compatible.

For the .gitattributes change, see [this bp README section](https://github.com/openshift/boilerplate/blob/180f2994b9c9068136c0ca131cb3bf8bb1a23e96/README.md#consumer-philosophy).

**Comment by RiRa12621** [comment]
/unhold
Can we add that to the description and have a proper title next time please?

**Pull request merged**
