### PR TITLE
Jira OSD-6289: bump operator-sdk version

### PR DESCRIPTION
**Pull request by georgettica**
this is done be looking at https://v1-3-x.sdk.operatorframework.io/docs/upgrading-sdk-version/v1.3.0/ and following along

### CODE REVIEW

**Comment by georgettica** [comment]
/hold
untested, but @dofinn wanted this change to land here :)

**Comment by RiRa12621** [comment]
yeah definitely holding that until it's tested and also @jharrington22 looked at it

**Comment by georgettica** [comment]
sure, now that it's done we can get the ball rolling on it

**Comment by 2uasimojo** [comment]
Does anything need to be regenerated? Whenever we upgraded within 0.* we had to regenerate k8s, crds, and openapi.

**Comment by georgettica** [comment]
controller-gen didn't regenerate, so I don't think it's required.

But I haven't deployed and tested intensively

**Comment by RiRa12621** [comment]
@georgettica misses Jira or BZ link

**Comment by georgettica** [comment]
there isn't one 😨

**Comment by RiRa12621** [comment]
We should create one to track it

**Comment by georgettica** [comment]
Created a card, will link on Sunday

**Comment by georgettica** [comment]
do we want to close it now and open later?
I think so..
so unless no one wants to revive it'll close

**Pull request closed without merging**
