### PR TITLE
OSD-14462 create a packaging-operator package for route-monitor-operator

### PR DESCRIPTION
**Pull request by yithian**
By installing the clusterpackage defined in deploy/package.yaml , packaging-operator will install route-monitoring-operator for [OSD-14462](https://issues.redhat.com//browse/OSD-14462)

### CODE REVIEW

**Review by mjlshen — APPROVED** [review]
/lgtm

**Review by sam-nguyen7 — COMMENTED** [review]
/lgtm

**Comment by thetechnick** [comment]
Hey folks, I was looking at Package Operator logs in staging and see this frequently:
```
2023-02-15T19:24:11Z    ERROR   Reconciler error        {"controller": "clusterobjectset", "controllerGroup": "package-operator.run", "controllerKind": "ClusterObjectSet", "ClusterObjectSet": {"name":"route-monitor-operator-6865b5956b"}, "namespace": "", "name": "route-monitor-operator-6865b5956b", "reconcileID": "3d8f20b7-90dd-43e9-86d8-527bf5c3cdac", "error": "creating: customresourcedefinitions.apiextensions.k8s.io \"clusterurlmonitors.monitoring.openshift.io\" already exists"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/controller/controller.go:235
```
This log was taken from `hs-mc-op846kea0`

The clusterurlmonitors.monitoring.openshift.io is already installed on the cluster via OLM so PKO is logging this conflict here and cannot continue. PKO is not yet surfacing all these errors to users in the API until https://issues.redhat.com/browse/MTSRE-934 is tackeled.

**Review by sam-nguyen7 — COMMENTED** [review]
/lgtm

Peer reviewed with @yithian . This process is currently not automated and we'll need to update RMO's cicd to use `make everything` instead of `make build-push`. We'll be writing a card to improve on this in the future.

**Pull request merged**
