### PR TITLE
fix(dockerfile): stop pulling from dockerhub

### PR DESCRIPTION
**Pull request by georgettica**
same as aws-account-operator

### CODE REVIEW

**Comment by georgettica** [comment]
hahah

**Comment by georgettica** [comment]
pulling `316.01MB` locally is not something that will go well

**Comment by georgettica** [comment]
you got it @RiRa12621

**Review by NautiluX — COMMENTED** [review]
/lgtm
/approve

**Comment by RiRa12621** [comment]
/lgtm
Love to see vendoring

**Pull request merged**
