### PR TITLE
change the blackbox deployment namespace as per OSD-6298

### PR DESCRIPTION
**Pull request by sulmer-redhat**

### CODE REVIEW

**Comment by georgettica** [comment]
/hold
can you look at something in the code?
we think that if someone changes the status.servicemonitorref it will cause a servicemonitor leak

**Comment by RiRa12621** [comment]
/hold
@sulmer-redhat that doesn't look like a test flake but rather the change causing failing tests

**Comment by georgettica** [comment]
@sulmer-redhat as this is related to #78 maybe close this?

**Pull request closed without merging**
