### PR TITLE
Jira OSD-6055: add serviceMonitor reference

### PR DESCRIPTION
**Pull request by Tessg22**
Co-authored-by: sulmer-redhat <sulmer@redhat.com>
Co-authored-by: NautiluX <mdewald@redhat.com>

### CODE REVIEW

**Comment by RiRa12621** [comment]
@Tessg22 please add a Jira card or BZ

**Comment by Tessg22** [comment]
Jira card [OSD-6055](https://issues.redhat.com/browse/OSD-6055).

**Review by NautiluX — COMMENTED** [review]
/lgtm

**Pull request merged**
