### PR TITLE
Test statically linked

### PR DESCRIPTION
**Pull request by RiRa12621**
test statically linked to comply with sec requirements

### CODE REVIEW

**Comment by georgettica** [comment]
/lgtm
seems like a straightforward thing to me

**Comment by RiRa12621** [comment]
/hold
Needs more testing

**Comment by georgettica** [comment]
Same issue I got in RMO v1 stuff

Maybe @ramonbutter can help (when he is online)

**Comment by RiRa12621** [comment]
I didn't have time yet to look into it tbh

**Pull request closed without merging**
