### PR TITLE
OSD-10503: build(Dockerfile): update ubi-micro image tag

### PR DESCRIPTION
**Pull request by Tessg22**
Update ubi-micro image tag from latest to versioned.

### CODE REVIEW

**Comment by georgettica** [comment]
/lgtm
/approve
another step in the right direction

**Comment by Nikokolas3270** [comment]
Are we sure we want we want to get rid of `latest`?
As said here, using `latest` is widely accepted & used:
https://coreos.slack.com/archives/CCX9DB894/p1651506047185529?thread_ts=1651504202.651549&cid=CCX9DB894
As discussed yesterday, fixing a version for a dependency also has it issues if we forget to bump that version from time to time.
I am not against using a fixed version, but then, for the sake of consistency, it would be good to encourage the practice elsewhere as well.

**Comment by georgettica** [comment]
I guess using latest is some sort of automation, but we should have a process of rolling the image across the fleet / checking the digests of the images on the fleet to make sure we are actually on top of this problem

**Comment by shibumi** [comment]
I agree with @georgettica  here.. having `latest` is nice for the sake of automation, but we shouldn't sacrifice deterministic behavior for it.

**Pull request merged**
